### PR TITLE
fix - in ZLIB_RUNTIME_VERSION

### PR DESCRIPTION
**Pull request by pmp-p**
could help for other platform so dit not check =='android'

### CODE REVIEW

**Comment by vstinner** [comment]
Is this change specific to API 19?

**Comment by pmp-p** [comment]
not so sure, that symbol "1.2.8-linuxfoundation-mods-v1"  was found in a android kitkat rom in /system/lib/libz.so there's no guarantee it does not exists with "-" on other zlib build.
( and obviously test_zlib is already dealing with existing inconsistent version scheme )

**Comment by pmp-p** [comment]
seems worse on android 4.4.4 https://answers.unrealengine.com/storage/attachments/61439-log.txt
"1.2.8.f-linuxfoundation-mods-v1"
my patch does not cover all cases

**Comment by pmp-p** [comment]
seems ok now

**Comment by vstinner** [comment]
You didn't reply. Is this bug specific to API 19? If not, please open an issue on bugs.python.org and propose a PR on master.

**Comment by pmp-p** [comment]
i can't be sure it is android and api specific so opening an issue. 
https://bugs.python.org/issue32682

**Comment by vstinner** [comment]
Closed, since a dedicated PR was written:  https://bugs.python.org/issue32682

**Pull request closed without merging**
